### ISSUE TITLE
Doc build is broken due to incorrect path to image file

### ISSUE THREAD

**Issue by JSchripsema-IDM** [InstituteforDiseaseModeling/EMOD-Generic-Scripts#7]
The Sphinx build is producing the following error:

/home/docs/checkouts/readthedocs.org/user_builds/institute-for-disease-modeling-emod-generic-scripts/checkouts/latest/docs/examples/model_rubella01.rst:20: WARNING: image file not readable: examples/figures/ref_rcv_demog_ss.png

You need to update the path to use the relative path from the model_rubella01.rst file: figures/ref_rcv_demog_ss.png

**Comment by kfrey-idm** [comment]
Should be fixed now, thanks!
